### PR TITLE
Remove window.loadExtensionView.

### PR DESCRIPTION
**Pull request by dompuiu**
## Description

Remove window.loadExtensionView from sandbox.

## Motivation and Context

There are better ways to test the extension views.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by brenthosie — COMMENTED** [review]
What's the catalyst behind this change and will it unexpectedly introduce problems for customers relying on it?

**Comment by dompuiu** [comment]
@Aaronius Would you be kind and review this change? It's related to the last email you sent to us where you said you no longer need it.

**Review by Aaronius — APPROVED** [review]
Looks good. To answer @brenthosie's question, I initially added this functionality because I thought it was a good way for extension developers to be able to test their extensions in an automated fashion using something like TestCafe and Cypress. We thought we needed this for the web SDK extension and we actually used it for a couple years, but recently devised a better approach that doesn't require us to use the sandbox by mocking the extension bridge coming from Akamai. It simplified code and sped up the tests as well, so I would advise anyone else to take a similar approach instead of using this `loadExtensionView` functionality.

I don't know if anyone else is using this functionality currently, but if they are, then this removal will force them to use a different approach. As such, this should be released as a major version.

**Comment by Aaronius** [comment]
For reference, here's what we ended up doing instead. When running functional tests, our extension requests the extension bridge from Akamai and we return a mock extension bridge file instead that allows our functional tests to call the extension's `init`, `getSettings`, and `validate` methods as though it were Launch. We're leveraging network mocking capabilities built into TestCafe, though other frameworks have similar functionality. Here's the [mock extension bridge file we use](https://github.com/adobe/reactor-extension-alloy/blob/react-spectrum/test/functional/helpers/extensionBridgeMock.js) in place of the real extension bridge. This allows us to not have to run the extension within reactor-sandbox or even an iframe when running functional tests, while still being able to test the `init`, `getSettings`, and `validate` logic of the extension. If any other extension developers run into the same need, you could point them to this approach.

**Pull request merged**
