### PR TITLE
Added logging & clarified validation error message

### PR DESCRIPTION
**Pull request by markhicken**
## Description
When running validate in sandbox, it was not intuitive to me that it also validates the schema. I expected it to run my validate function and return only those results (a promise/boolean). When it failed with a schema error, I found myself digging through my `extension.json`. 

My `getSettings` function was the culprit, returning a number when a string was expected. So the error was correct, but it could do more to guide me to the source of the problem. I believe this error only occurs when `validate` succeeds AND the result of `getSettings` does not match the schema.

In addition to clarifying the error message, this PR adds logging for `init()`, `validate()` and `getSettings()`.

## Screenshots (if appropriate):
Screen Shot 2020-02-28 at 6 14 29 PM

Screen Shot 2020-02-28 at 6 14 52 PM

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by markhicken** [comment]
@Aaronius, I've added logging and updated the error message as we discussed. I wanted to add the schema validation errors as well, but I found that `ajv.errors` was null after validation failed. We could probably figure this out but I need to limit the amount of time I dump into this PR. I think it's good enough as is to provide value to extension devs. No rush, but let me know what you think ok?

**Comment by dompuiu** [comment]
@markhicken What is the purpose of LOGGING_ENABLED? Can you set it to false from the command line?

**Comment by Aaronius** [comment]
@markhicken let me know what you'd what you decide to do with the `LOGGING_ENABLED` flag, then I'll merge.

**Comment by markhicken** [comment]
On the Logging flag. My original thought was to make a UI switch to enable/disable it. I'm not sure there's any need to disable it though, so I'll go ahead and remove the variable for now.

**Comment by markhicken** [comment]
Done. Ready to merge if you are.

**Comment by Aaronius** [comment]
Thanks for contributing! Published as v10.8.0.

**Comment by markhicken** [comment]
Awesome! Thx!

**Pull request merged**
